name:             "Haneen"
description:      "personal website"
title:            "Haneen"
url:              http://haneensa.github.io
permalink:        pretty
highlighter:      rouge
maarkdown:        redcarpet 
plugins:
        - jekyll-feed
